version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.14.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          name: Save dependency cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Run Tests
          environment:
            JEST_JUNIT_OUTPUT: "test-results/js-unit-test-results.xml"
          command: npm run test:ci

      - store_test_results:
          path: test-results
